### ISSUE TITLE
1.15.1 Support ? 

### ISSUE THREAD

**Issue by RasmonT** [Niall7459/HolographicExtension#14]
Hello, 

is there some dev build or snapshot that works well with 1.15.1 spigot ? Plugin commands seems to work but placeholders does not.. (I want to update my survival from 1.13.2 to 1.15.1) 
Also there are some errors that console prints. 

https://pastebin.com/2vFLbJZp

Best regards.

**Comment by Niall7459** [comment]
Hi, you may download the source hear and compile it, currently a 1.15 release on spigot is expected next week or later this week

Thank you

**Comment by RasmonT** [comment]
Ah i see... Unfortunately i do not have experience with plugin compilations, what do you recommend to compile your source to a .jar file?

**Comment by Niall7459** [comment]
Hi, I managed to update it just now, the new version should appear on spigot in a few moments.

Thanks

**Comment by RasmonT** [comment]
Very kind of you, thank you! Placeholders are working well.
