### ISSUE TITLE
Console Error on 1.14.2

### ISSUE THREAD

**Issue by ronc617** [Niall7459/HolographicExtension#9]
Any Plans for 1.14.2 update ?
FYI if it helps with updates
getting the following errors running the latest version of spigot 1.14.2 / Protocollib / Holodisplay
https://pastebin.com/PAt8MCjU

**Comment by Wealthyturtle** [comment]
Having a similar error-spam in regards to the `Unhandled exception occured in onPacketSending(PacketEvent) for HolographicExtension` issue: https://pastebin.com/raw/cDfU1rwc

**Comment by ronc617** [comment]
https://pastebin.com/M5zqwUkd just another one to compare

**Comment by Niall7459** [comment]
I'm expecting this is a ProtocolLib issue. I will contact them. Any chance you could test `{player}` in a hologram and tell me if that it working?

**Comment by Wealthyturtle** [comment]
![image](https://user-images.githubusercontent.com/19924575/59565334-c19ebf80-9084-11e9-88de-331f76f39368.png)
Tried all of those, none worked

**Comment by ronc617** [comment]
any luck on this issue yet?
also noticed that placeholder stopped updating
i use it for islandlevel for bskyblock
not sure if it is because holo extensions or bskyblock

**Comment by Niall7459** [comment]
Alright, I’m pretty sure it’s a protocol lib issue, that’s what’s breaking the placeholders.
I’m going to raise an issue on their GitHub for this. I will keep you updated.

**Comment by Niall7459** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/637

**Comment by Niall7459** [comment]
@ronc617 I've raised an issue on ProtocolLib's repo. For the moment I'm expecting it to be an issue with ProtocolLib as the `{player}` placeholder provided by HolographicDisplays it self is not working. Unless something needs specifically updating for 1.14. I will keep you posted.

**Comment by ronc617** [comment]
Sounds good thank you for the update

**Comment by ronc617** [comment]
Just FYI
Updated to the latest protocol dev build and 1.14.3 and everything seems to
be working now for me

**Comment by ronc617** [comment]
guess i spoke to soon issue still seems to be there
https://pastebin.com/mCkbwCiZ
that is running latest protocol along with spigot 1.14.3

**Comment by Niall7459** [comment]
Alright I will forward this to the ProtocolLib team.

**Comment by suiiciiide** [comment]
same thing is happening to me any progress on the issue

**Comment by suiiciiide** [comment]
> guess i spoke to soon issue still seems to be there
> https://pastebin.com/mCkbwCiZ
> that is running latest protocol along with spigot 1.14.3

Is it fixed yet i need to know how to fix it xD

**Comment by Niall7459** [comment]
Hi, the issue is with ProtocolLib, you may track its progress here: https://github.com/dmulloy2/ProtocolLib/issues/637

**Comment by successed** [comment]
i have more problem : http://bin.shortbin.eu:8080/QggbCzj5hk

**Comment by Niall7459** [comment]
Fixed, please update to latest ProtocolLib
